version: '3'

services:
    front_end:
        build:
            context: front_end/
            dockerfile: Dockerfile
        container_name: front_end
        restart: always
        ports: 
            - "5000:5000"
        depends_on:
            - api
    api:
        build:
            context: api/
            dockerfile: Dockerfile
            args: 
                - FURY_USERNAME=${FURY_USERNAME}
                - FURY_TOKEN=${FURY_TOKEN} # passes in token to dockerfile via arg
        container_name: api
        restart: always