version: '3'

services:
    front_end:
        build:
            context: front_end/
            dockerfile: Dockerfile
        container_name: front_end
        restart: always
        ports: 
            - "5000:5000"